#!/bin/bash

(cd tarp && go build && mv tarp ../tarpcmd) || {
    echo "BUILD FAILED"
    exit 3
}

cd tests
for fname in *.bash; do
    echo
    echo === $fname 1>&2
    echo
    tarp=../tarpcmd bash -e ./$fname || {
        echo TEST $fname FAILED
        exit 1
    }
done

rm -f tarpcmd
