name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libczmq-dev libzmq-dev libsodium-dev
        version: 1.0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: |
          make bin/tarp

    # TODO enable testing. Currently failing:
    # Error: mpio.go:12:2: missing go.sum entry for module providing package github.com/shamaton/msgpack (imported by github.com/tmbdev/tarp/dpipes); to add:
    # 	go get github.com/tmbdev/tarp/dpipes
    # Error: mpio.go:13:2: missing go.sum entry for module providing package gopkg.in/zeromq/goczmq.v4 (imported by github.com/tmbdev/tarp/dpipes); to add:
    # 	go get github.com/tmbdev/tarp/dpipes
    # make: *** [Makefile:18: test] Error 1
    # Error: Process completed with exit code 2.

    # - name: Build
    #   run: |
    #       make test
