name: Release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'      

permissions:
    contents: write
    packages: write

jobs:
  build-binaries:
    name: Release go binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      if: ${{ matrix.os == 'ubuntu-latest'}}
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libczmq-dev libzmq-dev libsodium-dev
        version: 1.0

    - name: Install dependencies
      if: ${{ matrix.os == 'macos-latest'}}
      run: |
          brew install libsodium zmq czmq zeromq

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.5

    - name: Build binaries
      run: |
        build_dir=${GITHUB_WORKSPACE}/build
        mkdir -p ${build_dir}
        export TARP_BIN_NAME=${build_dir}/tarp-$(go env GOOS)-$(go env GOARCH)
        make bin/tarp
      env:
        GO_BUILD_FLAGS: -ldflags '-X main.version=`date -Iseconds`' -tags static -installsuffix static -extldflags '-static'


    - name: List binaries
      run: |
        ls -la
        ls -la build/

    - uses: actions/upload-artifact@v3
      with:
        name: executables
        path: ${{ github.workspace }}/build/tarp-*

  release:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: executables
        path: ${{ github.workspace }}/build/
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ github.workspace }}/build/tarp-*

